# 异常

## 一、异常体系结构

 * java.lang.Throwable
    * 		|-----java.lang.Error:一般不编写针对性的代码进行处理。
    * |-----java.lang.Exception:可以进行异常的处理
       * |------编译时异常(checked)：编译不能通过，不能生成.class字节码
          * |-----IOException
             * 						|-----FileNotFoundException
          * 					|-----ClassNotFoundException
       * |------运行时异常(unchecked,**RuntimeException**)：编译可以通过，在运行时出错
          * 					|-----NullPointerException
          * 					|-----ArrayIndexOutOfBoundsException
          * 					|-----ClassCastException
          * 					|-----NumberFormatException
          * 					|-----InputMismatchException
          * 					|-----ArithmeticException

## 二、异常的处理：抓抛模型

 * 过程一："抛"：程序在正常执行的过程中，一旦出现异常，就会在异常代码处生成一个对应异常类的对象，并将此对象**抛出**。<u>一旦抛出对象以后，其后的代码就不再执行</u>。
    * 关于异常对象的产生：
       * 		系统自动生成的异常对象
       * 手动的生成一个异常对象，并抛出（使用throw自己生成异常抛出）
 * 过程二："抓"：可以理解为异常的**处理**方式：① try-catch-finally  ② throws

### 1. 异常处理的方式一：try-catch-finally的使用

```Java
 try{
 //可能出现异常的代码
 }catch(异常类型1 变量名1){
 //处理异常的方式1
 }catch(异常类型2 变量名2){
 //处理异常的方式2
 }catch(异常类型3 变量名3){
 //处理异常的方式3
 }
 ....
 finally{
 //一定会执行的代码
 }
```

**说明：**

 * 1. finally是可选的。
 * 2. 使用try将可能出现异常代码包装起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，去catch中进行匹配
 * 3. 一旦try中的异常对象匹配到某一个catch时，就进入catch中进行异常的处理。**一旦处理完成，就跳出当前的try-catch结构（在没有写finally的情况）。继续执行其后的代码**
 * 4. **catch中的异常类型如果没有子父类关系，则谁声明在上，谁声明在下无所谓。catch中的异常类型如果满足子父类关系，则要求子类一定声明在父类的上面。否则，报错**
 * 5. 常用的异常对象处理的方式： ① String  getMessage() ② printStackTrace()
 * 6. try-catch-finally结构可以嵌套

**理解：**

 * 体会1：使用try-catch-finally处理编译时异常，**使得程序在编译时就不再报错，但是运行时仍可能报错，相当于将一个编译时可能出现的异常，延迟到运行时出现。**
 * 体会2：开发中，由于**运行时异常**比较常见，所以我们**通常就不针对运行时异常编写try-catch-finally了**，针对于编译时异常，我们说一定要考虑异常的处理。

### 2.异常处理的方式二：throws + 异常类型

 * 1. **"throws + 异常类型"写在方法的声明处**。指明此方法执行时，可能会抛出的异常类型

   ```Java
   	public static void method1() throws FileNotFoundException,IOException{  
           /** 在method1()这个函数不对异常进行处理，但是调用method的上一级函数需要对                                                                              * 这个异常进行处理，可以进行try+catch，也可以继续将这个异常继续往上抛，
            * 一般抛到主函数就要进行处理，不再往上抛
            */
   	...pass...
   	}
   ```

 * 2. **体会：try-catch-finally:真正的将异常给处理掉了。throws的方式只是将异常抛给了方法的调用者，并没有真正将异常处理掉。**  

 * 3. 开发中如何选择使用try-catch-finally 还是使用throws？	

   - 3.1 如果父类中被重写的方法没有throws方式处理异常，则子类重写的方法也不能使用throws，意味着如果子类重写的方法中有异常，必须使用try-catch-finally方式处理。

    *   <u>3.2 执行的方法a中，先后又调用了另外的几个方法，这几个方法是递进关系执行的。我们建议这几个方法使用throws的方式进行处理。而执行的方法a可以考虑使用try-catch-finally方式进行处理。</u>

### 3. try-catch-finally中finally的使用：

 * 1.finally是可选的
 * 2.finally中声明的是**一定会被执行的代码，即使catch中又出现异常了，try中有return语句，catch中有return语句等情况**。
 * 3.像数据库连接、输入输出流、网络编程Socket等资源，<u>JVM是不能自动的回收的</u>，我们需要自己手动的进行资源的释放。此时的资源释放，就需要声明在finally中。

### 4. 注意点

方法重写的规则之一：
 * 子类重写的方法抛出的异常类型**不大于**父类被重写的方法抛出的异常类型。

```Java
class SuperClass{  
   public void method() throws IOException{
      
   }   
}

class SubClass extends SuperClass{
   public void method()throws FileNotFoundException{
      
   }
}
```

## 三、如何自定义异常类？

 * 1. 继承于现有的异常结构：RuntimeException（运行时异常） 、Exception（编译时异常）
 * 2. 提供全局常量：serialVersionUID
 * 3. 提供重载的构造器

```Java
class MyException extends Exception{  // 1-继承Exception
    // 2-序列号
    static final long serialVersion = -156435138L;
    // 3-构造方法
    public MyException(){

    }

    public MyException(String msg) {
        super(msg);
    }

}
```

## 四、手动抛出异常：throw

```java
public class Test {

    public static void main(String[] args) throws MyException {

        int a = 10,b=0;
        if (b == 0) {
            throw new MyException("除数不能为0");
        }
    }
}
```

